# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usermodel_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelIndex',
            fields=[
                ('usermodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.UserModel')),
                ('tree', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
