# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161230_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='preview',
            field=models.ImageField(default=None, upload_to='static/previews/'),
        ),
    ]
