# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usermodel_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='descriptor',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='file',
            field=models.FileField(upload_to='models/'),
        ),
    ]
