# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170410_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='descriptor',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
