# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='models/')),
                ('indexed', models.BooleanField(default=False)),
                ('descriptor', models.TextField(blank=True, default='[]', null=True)),
                ('preview', models.ImageField(default=None, upload_to='static/previews/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelIndex',
            fields=[
                ('usermodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fend.UserModel')),
                ('tree', models.TextField()),
            ],
        ),
    ]
