# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 15:47
from __future__ import unicode_literals

import api.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='models/', validators=[api.validators.validate_file_extension])),
                ('indexed', models.BooleanField(default=False)),
                ('descriptor', models.TextField(blank=True, default='[]', null=True)),
                ('preview', models.ImageField(default=None, upload_to='static/previews/')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faces', models.TextField(blank=True, default='[]', null=True)),
                ('descriptor', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel')),
            ],
        ),
    ]
