# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:13
from __future__ import unicode_literals

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='models/', validators=[api.validators.validate_file_extension])),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('indexed', models.BooleanField(default=False)),
                ('descriptor', models.TextField(blank=True, default='[]', null=True)),
                ('preview', models.ImageField(default=None, upload_to='static/previews/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelIndex',
            fields=[
                ('usermodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.UserModel')),
                ('tree', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to='api.UserModel'),
        ),
    ]
