# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelnode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel'),
        ),
    ]
