# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170817_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelnode',
            name='faces',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'face_normals': [], 'faces': [], 'metadata': [], 'vertices': []}),
        ),
    ]
