# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_indexed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='indexed',
        ),
    ]
