# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170817_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodelnode',
            old_name='faces',
            new_name='model',
        ),
    ]
